version: '3.8'
services:
  pythonapp:
    build: ./Python/
    networks:
      - mynetwork
    command: sh -c "sleep 20s ; python3 ./main.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    networks:
      - mynetwork
    environment:
      MYSQL_DATABASE: 'arboles'
      MYSQL_ROOT_PASSWORD: 'arbolesroot123'
    ports:
      - 3306:3306

networks:
  mynetwork:
    driver: bridge